// SPDX-License-Identifier: BUSL-1.1

/**
 * Thin wrappers around the Supabase Cloud Auth (GoTrue) HTTP API used by
 * the auth Edge Functions (#1886).
 *
 * These functions hit Supabase Auth directly rather than going through the
 * `@supabase/supabase-js` client, so the Deno runtime stays lightweight
 * and cold-starts fast. The wire format follows GoTrue's documented API.
 *
 * @module
 */

import { requireEnv } from './env.ts';

/** Shape of a successful Supabase token response. */
export interface SupabaseTokenResponse {
  /** Short-lived (1h default) access JWT. */
  access_token: string;
  /** Seconds until {@link access_token} expires. */
  expires_in: number;
  /** Rotated single-use refresh token. */
  refresh_token: string;
  /** Always `bearer` for Supabase. */
  token_type: 'bearer';
}

/** Error payload returned by Supabase Auth / GoTrue. */
export interface SupabaseAuthError {
  /** Upstream HTTP status, absent when fetch failed before a response. */
  status?: number;
  /** Stable Supabase Auth error code when present. */
  code?: string;
  /** Legacy OAuth-style error string when present. */
  error?: string;
  /** Human-readable upstream message when present. */
  message?: string;
}

/** Classified refresh-token grant result. */
export type RefreshGrantResult =
  | { kind: 'success'; tokens: SupabaseTokenResponse }
  | { kind: 'invalid_refresh_token'; error: SupabaseAuthError }
  | { kind: 'transient_error'; error: SupabaseAuthError }
  | { kind: 'unknown_error'; error: SupabaseAuthError };

/** PKCE material generated by `auth-oauth-start`. */
export interface PkceMaterial {
  /** Random URL-safe verifier (43–128 chars). */
  codeVerifier: string;
  /** SHA-256(verifier), base64url-encoded. */
  codeChallenge: string;
}

/** Identity providers supported by these endpoints. */
export const SUPPORTED_PROVIDERS = ['google', 'github', 'apple'] as const;
export type AuthProvider = (typeof SUPPORTED_PROVIDERS)[number];

/** Type guard for {@link AuthProvider}. */
export function isSupportedProvider(value: string): value is AuthProvider {
  return (SUPPORTED_PROVIDERS as readonly string[]).includes(value);
}

/**
 * Exchange an email/password pair for a Supabase access + refresh token
 * pair. Returns the GoTrue JSON or null on a 4xx response (invalid creds
 * etc.) so callers can map it to a generic error.
 */
export async function passwordGrant(
  email: string,
  password: string,
): Promise<SupabaseTokenResponse | null> {
  return await goTrueTokenRequest('password', { email, password });
}

/**
 * Exchange a refresh token for a new (access, refresh) pair. Supabase
 * rotates the refresh token on every successful call, so the caller
 * MUST persist the new value (overwrite the HttpOnly cookie).
 */
export async function refreshGrant(refreshToken: string): Promise<SupabaseTokenResponse | null> {
  const result = await refreshGrantWithClassification(refreshToken);
  return result.kind === 'success' ? result.tokens : null;
}

/**
 * Exchange a refresh token and classify failures so callers can avoid
 * clearing cookies for transient or ambiguous upstream errors.
 */
export async function refreshGrantWithClassification(
  refreshToken: string,
): Promise<RefreshGrantResult> {
  const url = `${authUrl()}/token?grant_type=refresh_token`;
  let response: Response;
  try {
    response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: requireEnv('SUPABASE_ANON_KEY'),
      },
      body: JSON.stringify({ refresh_token: refreshToken }),
    });
  } catch (error) {
    return {
      kind: 'transient_error',
      error: { message: error instanceof Error ? error.message : String(error) },
    };
  }

  if (response.ok) {
    try {
      const json = (await response.json()) as Partial<SupabaseTokenResponse>;
      if (
        typeof json.access_token === 'string' &&
        typeof json.refresh_token === 'string' &&
        typeof json.expires_in === 'number'
      ) {
        return {
          kind: 'success',
          tokens: {
            access_token: json.access_token,
            refresh_token: json.refresh_token,
            expires_in: json.expires_in,
            token_type: 'bearer',
          },
        };
      }
    } catch (error) {
      return {
        kind: 'unknown_error',
        error: {
          status: response.status,
          message: error instanceof Error ? error.message : String(error),
        },
      };
    }

    return {
      kind: 'unknown_error',
      error: {
        status: response.status,
        message: 'Refresh response was missing token fields',
      },
    };
  }

  const authError = await readSupabaseAuthError(response);
  return { kind: classifyRefreshError(authError), error: authError };
}

/**
 * Exchange an OAuth authorization code + PKCE verifier for a token pair.
 *
 * This is the second leg of the PKCE flow. The verifier must match the
 * SHA-256 challenge sent during {@link buildAuthorizeUrl}.
 */
export async function pkceGrant(
  authCode: string,
  codeVerifier: string,
): Promise<SupabaseTokenResponse | null> {
  return await goTrueTokenRequest('pkce', {
    auth_code: authCode,
    code_verifier: codeVerifier,
  });
}

/**
 * Create a new email/password user in Supabase. Returns the user-issued
 * token pair when email confirmation is disabled (typical for alpha), or
 * null when Supabase responded with a 4xx (e.g. duplicate email).
 */
export async function signupUser(
  email: string,
  password: string,
): Promise<SupabaseTokenResponse | null> {
  const url = `${authUrl()}/signup`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      apikey: requireEnv('SUPABASE_ANON_KEY'),
    },
    body: JSON.stringify({ email, password }),
  });
  if (!response.ok) return null;
  // GoTrue returns either a session payload (no email confirmation) or a
  // user object (confirmation required). Treat the latter as "needs
  // confirmation" by returning null — callers map that to a 202 response.
  const body = (await response.json()) as Partial<SupabaseTokenResponse> & {
    user?: unknown;
  };
  if (typeof body.access_token === 'string' && typeof body.refresh_token === 'string') {
    return body as SupabaseTokenResponse;
  }
  return null;
}

/**
 * Revoke a Supabase refresh token. Best-effort: errors are swallowed
 * because logout must always clear the local cookie regardless of the
 * upstream result.
 */
export async function revokeRefreshToken(accessToken: string): Promise<void> {
  const url = `${authUrl()}/logout`;
  try {
    await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${accessToken}`,
        apikey: requireEnv('SUPABASE_ANON_KEY'),
      },
    });
  } catch {
    // Intentional swallow — logout proceeds locally regardless.
  }
}

/**
 * Build the Supabase OAuth authorize URL with PKCE.
 *
 * Supabase Cloud handles the provider hop (Google, GitHub, Apple) and
 * redirects back to {@link redirectTo} with a `?code=` query parameter
 * that the callback function consumes. We deliberately do NOT pass our
 * own `state` parameter: Supabase Cloud uses its own internal signed
 * state token and rejects arbitrary nonces with `bad_oauth_state`. PKCE
 * itself provides the CSRF protection — only the holder of the verifier
 * (stored in our HttpOnly cookie) can redeem the auth code.
 */
export function buildAuthorizeUrl(
  provider: AuthProvider,
  pkce: PkceMaterial,
  redirectTo: string,
): string {
  const params = new URLSearchParams({
    provider,
    code_challenge: pkce.codeChallenge,
    code_challenge_method: 'S256',
    redirect_to: redirectTo,
  });
  return `${authUrl()}/authorize?${params.toString()}`;
}

/**
 * Ask Supabase Auth to send a password recovery email.
 *
 * Returns the upstream status code so callers can keep account-existence
 * responses generic while still surfacing service outages.
 */
export async function requestPasswordRecovery(email: string, redirectTo: string): Promise<number> {
  const url = `${authUrl()}/recover?${new URLSearchParams({ redirect_to: redirectTo }).toString()}`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      apikey: requireEnv('SUPABASE_ANON_KEY'),
    },
    body: JSON.stringify({ email }),
  });
  return response.status;
}

/** Update a user's password using the recovery access token from Supabase. */
export async function updatePasswordWithAccessToken(
  accessToken: string,
  password: string,
): Promise<boolean> {
  const response = await fetch(`${authUrl()}/user`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${accessToken}`,
      apikey: requireEnv('SUPABASE_ANON_KEY'),
    },
    body: JSON.stringify({ password }),
  });
  return response.ok;
}

// ---------------------------------------------------------------------------
// PKCE / state generation
// ---------------------------------------------------------------------------

/**
 * Generate fresh PKCE material for an OAuth login attempt.
 *
 * The verifier is 32 random bytes, base64url-encoded (43 chars). The
 * challenge is SHA-256(verifier), base64url-encoded.
 */
export async function generatePkceMaterial(): Promise<PkceMaterial> {
  const codeVerifier = base64UrlEncode(randomBytes(32));
  const codeChallenge = await sha256Base64Url(codeVerifier);
  return { codeVerifier, codeChallenge };
}

// ---------------------------------------------------------------------------
// Helpers (internal)
// ---------------------------------------------------------------------------

function authUrl(): string {
  return `${requireEnv('SUPABASE_URL')}/auth/v1`;
}

type TokenRequestBody = Record<string, string>;

async function goTrueTokenRequest(
  grantType: 'password' | 'refresh_token' | 'pkce',
  body: TokenRequestBody,
): Promise<SupabaseTokenResponse | null> {
  const url = `${authUrl()}/token?grant_type=${grantType}`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      apikey: requireEnv('SUPABASE_ANON_KEY'),
    },
    body: JSON.stringify(body),
  });
  if (!response.ok) return null;
  const json = (await response.json()) as Partial<SupabaseTokenResponse>;
  if (
    typeof json.access_token !== 'string' ||
    typeof json.refresh_token !== 'string' ||
    typeof json.expires_in !== 'number'
  ) {
    return null;
  }
  return {
    access_token: json.access_token,
    refresh_token: json.refresh_token,
    expires_in: json.expires_in,
    token_type: 'bearer',
  };
}

const INVALID_REFRESH_TOKEN_CODES = new Set([
  'refresh_token_already_used',
  'refresh_token_not_found',
  'session_expired',
  'session_not_found',
]);

const TRANSIENT_REFRESH_ERROR_CODES = new Set([
  'conflict',
  'over_request_rate_limit',
  'request_timeout',
  'unexpected_failure',
]);

async function readSupabaseAuthError(response: Response): Promise<SupabaseAuthError> {
  const text = await response.text();
  const parsed = parseJsonObject(text);
  const code = getStringField(parsed, 'code') ?? getStringField(parsed, 'error_code');
  const error = getStringField(parsed, 'error');
  const message =
    getStringField(parsed, 'msg') ??
    getStringField(parsed, 'message') ??
    getStringField(parsed, 'error_description') ??
    (text.trim().length > 0 ? text : response.statusText);

  return {
    status: response.status,
    code,
    error,
    message,
  };
}

function classifyRefreshError(
  error: SupabaseAuthError,
): Exclude<RefreshGrantResult['kind'], 'success'> {
  const codeCandidates = [error.code, error.error].filter((value): value is string => !!value);
  if (codeCandidates.some((value) => INVALID_REFRESH_TOKEN_CODES.has(value.toLowerCase()))) {
    return 'invalid_refresh_token';
  }

  const searchable = codeCandidates
    .concat(error.message ?? '')
    .join(' ')
    .toLowerCase();
  if (
    /refresh[_\s-]+token.*(already[_\s-]+used|not[_\s-]+found|revoked|expired)/.test(searchable) ||
    /session.*(not[_\s-]+found|expired)/.test(searchable)
  ) {
    return 'invalid_refresh_token';
  }

  if (
    error.status === 408 ||
    error.status === 409 ||
    error.status === 429 ||
    (typeof error.status === 'number' && error.status >= 500) ||
    codeCandidates.some((value) => TRANSIENT_REFRESH_ERROR_CODES.has(value.toLowerCase()))
  ) {
    return 'transient_error';
  }

  return 'unknown_error';
}

function parseJsonObject(text: string): Record<string, unknown> | null {
  if (!text.trim()) return null;
  try {
    const parsed = JSON.parse(text) as unknown;
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

function getStringField(obj: Record<string, unknown> | null, field: string): string | undefined {
  const value = obj?.[field];
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function randomBytes(length: number): Uint8Array {
  const buf = new Uint8Array(length);
  crypto.getRandomValues(buf);
  return buf;
}

function base64UrlEncode(bytes: Uint8Array): string {
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  // btoa is available in Deno's globalThis.
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function sha256Base64Url(input: string): Promise<string> {
  const encoded = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest('SHA-256', encoded);
  return base64UrlEncode(new Uint8Array(digest));
}
