// SPDX-License-Identifier: BUSL-1.1

import type { BuiltinMerchantRule, RuleCategoryKey } from './types';

export const CATEGORY_ALIASES: Readonly<Record<RuleCategoryKey, readonly string[]>> = {
  groceries: ['groceries', 'grocery', 'food', 'food & dining', 'food and dining'],
  dining: ['dining', 'restaurants', 'restaurant', 'eating out', 'food', 'food & dining'],
  transportation: ['transportation', 'transport', 'travel', 'commute', 'gas', 'fuel', 'auto'],
  entertainment: ['entertainment', 'fun', 'media', 'streaming', 'subscriptions'],
  utilities: ['utilities', 'utility', 'housing', 'bills', 'monthly bills'],
  shopping: ['shopping', 'general merchandise', 'retail', 'household'],
  healthcare: ['healthcare', 'medical', 'health', 'pharmacy'],
};

export const BUILTIN_RULES: readonly BuiltinMerchantRule[] = [
  {
    id: 'builtin-groceries',
    categoryKey: 'groceries',
    merchants: [
      'whole foods',
      'trader joe',
      'kroger',
      'safeway',
      'costco',
      'walmart',
      'aldi',
      'publix',
      'wegmans',
      'meijer',
      'food lion',
      'giant eagle',
      'stop and shop',
      'h e b',
      'instacart',
      'fresh market',
    ],
  },
  {
    id: 'builtin-dining',
    categoryKey: 'dining',
    merchants: [
      'mcdonalds',
      'starbucks',
      'doordash',
      'uber eats',
      'grubhub',
      'chipotle',
      'subway',
      'chick fil a',
      'panera',
      'taco bell',
      'dunkin',
      'dominos',
      'pizza hut',
      'sweetgreen',
      'five guys',
    ],
  },
  {
    id: 'builtin-transportation',
    categoryKey: 'transportation',
    merchants: [
      'uber',
      'lyft',
      'shell',
      'chevron',
      'exxon',
      'bp',
      'speedway',
      'sunoco',
      'marathon',
      'wawa',
      'amtrak',
      'delta',
      'united',
      'southwest',
      'mta',
    ],
  },
  {
    id: 'builtin-entertainment',
    categoryKey: 'entertainment',
    merchants: [
      'netflix',
      'spotify',
      'disney plus',
      'hulu',
      'youtube premium',
      'apple tv',
      'max',
      'peacock',
      'steam',
      'playstation',
      'xbox',
      'ticketmaster',
      'audible',
      'paramount plus',
      'kindle',
    ],
  },
  {
    id: 'builtin-utilities',
    categoryKey: 'utilities',
    merchants: [
      'at and t',
      'att',
      'verizon',
      't mobile',
      'xfinity',
      'comcast',
      'spectrum',
      'pge',
      'pg and e',
      'comed',
      'duke energy',
      'con edison',
      'seattle city light',
      'water district',
      'national grid',
    ],
  },
  {
    id: 'builtin-shopping',
    categoryKey: 'shopping',
    merchants: [
      'amazon',
      'target',
      'best buy',
      'ebay',
      'etsy',
      'ikea',
      'home depot',
      'lowes',
      'nike',
      'old navy',
      'macys',
      'tj maxx',
      'wayfair',
      'sephora',
    ],
  },
  {
    id: 'builtin-healthcare',
    categoryKey: 'healthcare',
    merchants: [
      'cvs',
      'walgreens',
      'rite aid',
      'kaiser',
      'urgent care',
      'doctor',
      'hospital',
      'dentist',
      'optometrist',
      'labcorp',
      'quest diagnostics',
    ],
  },
] as const;
