// SPDX-License-Identifier: BUSL-1.1
// RecentTransactionsWidget.swift — Refs #380
import SwiftUI
import WidgetKit
struct TransactionsWidgetEntry: TimelineEntry { let date: Date; let transactions: [WidgetTransaction] }
struct TransactionsWidgetProvider: TimelineProvider {
    func placeholder(in context: Context) -> TransactionsWidgetEntry { .init(date:.now,transactions:WidgetTransaction.placeholders) }
    func getSnapshot(in context: Context, completion: @escaping (TransactionsWidgetEntry) -> Void) { completion(.init(date:.now,transactions:WidgetDataProvider.readTransactions(limit:context.family == .systemLarge ? 5:3))) }
    func getTimeline(in context: Context, completion: @escaping (Timeline<TransactionsWidgetEntry>) -> Void) { completion(Timeline(entries:[.init(date:.now,transactions:WidgetDataProvider.readTransactions(limit:context.family == .systemLarge ? 5:3))],policy:.after(Calendar.current.date(byAdding:.minute,value:30,to:.now)!))) }
}
struct RecentTransactionsWidget: Widget { let kind = "RecentTransactionsWidget"; var body: some WidgetConfiguration { StaticConfiguration(kind:kind,provider:TransactionsWidgetProvider()){entry in RecentTransactionsWidgetView(entry:entry).containerBackground(.fill.tertiary,for:.widget)}.configurationDisplayName(Text("Recent Transactions",comment:"Widget")).description(Text("View your most recent transactions.",comment:"Desc")).supportedFamilies([.systemMedium,.systemLarge]) } }
struct RecentTransactionsWidgetView: View {
    @Environment(\.widgetFamily) var family; let entry: TransactionsWidgetEntry
    var body: some View { VStack(alignment:.leading,spacing:8){HStack(spacing:4){Image(systemName:"list.bullet.rectangle.fill").font(.caption).foregroundStyle(.secondary).accessibilityHidden(true);Text("Recent Transactions",comment:"Hdr").font(.caption).foregroundStyle(.secondary);Spacer()};if entry.transactions.isEmpty{Text("No recent transactions.",comment:"Empty").font(.caption).foregroundStyle(.secondary).frame(maxWidth:.infinity,maxHeight:.infinity).accessibilityLabel(String(localized:"No recent transactions"))}else{let v=Array(entry.transactions.prefix(family == .systemLarge ? 5:3));VStack(spacing:family == .systemLarge ? 4:2){ForEach(v){t in row(t);if t.id != v.last?.id{Divider()}}}}}.accessibilityElement(children:.contain) }
    private func row(_ t: WidgetTransaction) -> some View { HStack(spacing:8){Image(systemName:t.categoryIcon).font(.caption).foregroundStyle(.secondary).frame(width:family == .systemLarge ? 24:20,height:family == .systemLarge ? 24:20).background(Circle().fill(.quaternary)).accessibilityHidden(true);VStack(alignment:.leading,spacing:1){Text(t.payee).font(.caption).fontWeight(.medium).lineLimit(1);if family == .systemLarge{Text(WidgetDateFormatter.relativeString(for:t.date)).font(.caption2).foregroundStyle(.secondary)}};Spacer();Text(t.isIncome ? "+":"-"+WidgetCurrencyFormatter.format(minorUnits:abs(t.amountMinorUnits),currencyCode:t.currencyCode)).font(.system(.caption,design:.rounded)).fontWeight(.semibold).monospacedDigit().foregroundStyle(t.isIncome ? FinanceWidgetColors.amountPositive:FinanceWidgetColors.amountNegative)}.accessibilityElement(children:.combine).accessibilityLabel(String(localized:"\(t.payee), \(t.isIncome ? "income":"expense"), \(WidgetCurrencyFormatter.formatForVoiceOver(minorUnits:abs(t.amountMinorUnits),currencyCode:t.currencyCode))")) }
}