package com.finance.core.insights

import com.finance.models.types.Cents
import com.finance.models.types.SyncId

/**
 * Sealed hierarchy of financial insights generated by [InsightEngine].
 * Each variant carries the context needed for display and action.
 * Use exhaustive `when` to ensure every insight type is handled.
 */
sealed class Insight {

    /** Spending velocity increased compared to the previous period. */
    data class SpendingUp(
        /** Ratio of current-period spending to previous-period spending (> 1.0). */
        val velocityRatio: Double,
        /** Absolute increase in cents. */
        val increaseAmount: Cents,
    ) : Insight()

    /** Spending velocity decreased compared to the previous period. */
    data class SpendingDown(
        /** Ratio of current-period spending to previous-period spending (< 1.0). */
        val velocityRatio: Double,
        /** Absolute decrease in cents. */
        val decreaseAmount: Cents,
    ) : Insight()

    /** A budget is on track — utilization is at a healthy level for the period elapsed. */
    data class BudgetOnTrack(
        val budgetId: SyncId,
        val budgetName: String,
        val utilization: Double,
    ) : Insight()

    /** A budget is at risk of being exceeded before the period ends. */
    data class BudgetAtRisk(
        val budgetId: SyncId,
        val budgetName: String,
        val utilization: Double,
        /** Projected overage in cents if current pace continues. */
        val projectedOverage: Cents,
    ) : Insight()

    /** A savings goal is ahead of the pace needed to reach its target by deadline. */
    data class GoalAhead(
        val goalId: SyncId,
        val goalName: String,
        /** Current progress as a fraction 0.0–1.0. */
        val progress: Double,
        /** Expected progress based on elapsed time — always <= [progress]. */
        val expectedProgress: Double,
    ) : Insight()

    /** A savings goal is behind the pace needed to reach its target by deadline. */
    data class GoalBehind(
        val goalId: SyncId,
        val goalName: String,
        /** Current progress as a fraction 0.0–1.0. */
        val progress: Double,
        /** Expected progress based on elapsed time — always > [progress]. */
        val expectedProgress: Double,
    ) : Insight()

    /** Savings rate improved compared to the previous period. */
    data class SavingsImproved(
        /** Current savings rate as a percentage (0.0–100.0). */
        val currentRate: Double,
        /** Previous savings rate as a percentage (0.0–100.0). */
        val previousRate: Double,
    ) : Insight()
}
