// SPDX-License-Identifier: BUSL-1.1

import Foundation

enum LucideMapping {
    static let mapping: [IconToken: String] = [
        .home: "home",
        .dashboard: "layout-dashboard",
        .accounts: "users",
        .transactions: "receipt-text",
        .budgets: "calculator",
        .goals: "target",
        .reports: "chart-column",
        .insights: "lightbulb",
        .settings: "settings",
        .search: "search",
        .notifications: "bell",
        .profile: "circle-user-round",
        .wallet: "wallet",
        .cash: "banknote",
        .bank: "landmark",
        .creditCard: "credit-card",
        .debitCard: "credit-card",
        .savings: "piggy-bank",
        .investment: "trending-up",
        .loan: "hand-coins",
        .mortgage: "house-plus",
        .netWorth: "scale",
        .balance: "scale",
        .income: "arrow-down-to-line",
        .expense: "arrow-up-from-line",
        .transfer: "arrow-left-right",
        .recurring: "repeat",
        .bill: "file-text",
        .budget: "calculator",
        .goal: "flag",
        .piggyBank: "piggy-bank",
        .chartLine: "chart-line",
        .chartBar: "chart-bar",
        .chartPie: "chart-pie",
        .add: "plus",
        .edit: "pencil",
        .delete: "trash-2",
        .save: "save",
        .cancel: "circle-x",
        .close: "x",
        .check: "check",
        .refresh: "refresh-cw",
        .sync: "refresh-ccw",
        .download: "download",
        .upload: "upload",
        .export: "file-up",
        .import: "file-down",
        .filter: "funnel",
        .sort: "arrow-up-down",
        .scan: "scan-line",
        .copy: "copy",
        .share: "share-2",
        .success: "circle-check",
        .warning: "triangle-alert",
        .error: "circle-alert",
        .info: "info",
        .pending: "clock",
        .locked: "lock",
        .unlocked: "lock-open",
        .online: "wifi",
        .offline: "wifi-off",
        .secure: "shield-check",
        .checkingAccount: "landmark",
        .savingsAccount: "piggy-bank",
        .cashAccount: "wallet",
        .creditAccount: "credit-card",
        .investmentAccount: "chart-line",
        .loanAccount: "hand-coins",
        .mortgageAccount: "house",
        .retirementAccount: "palm-tree",
        .categoryFood: "utensils",
        .categoryGroceries: "shopping-basket",
        .categoryRestaurants: "chef-hat",
        .categoryTransport: "car",
        .categoryFuel: "fuel",
        .categoryShopping: "shopping-bag",
        .categoryEntertainment: "popcorn",
        .categoryTravel: "plane",
        .categoryHealth: "heart-pulse",
        .categoryFitness: "dumbbell",
        .categoryHome: "house",
        .categoryUtilities: "plug",
        .categoryEducation: "graduation-cap",
        .categoryGifts: "gift",
        .categoryTaxes: "receipt",
        .categoryInsurance: "shield",
        .categorySubscriptions: "repeat",
        .categorySalary: "badge-dollar-sign",
    ]
}

func lucideNameFor(_ token: IconToken) -> String {
    LucideMapping.mapping[token] ?? token.rawValue
}
