// SPDX-License-Identifier: BUSL-1.1

import Foundation

enum SFSymbolsMapping {
    static let mapping: [IconToken: String] = [
        .home: "house",
        .dashboard: "gauge.with.dots.needle.67percent",
        .accounts: "person.2",
        .transactions: "list.bullet.rectangle",
        .budgets: "chart.pie",
        .goals: "target",
        .reports: "doc.text.magnifyingglass",
        .insights: "lightbulb",
        .settings: "gearshape",
        .search: "magnifyingglass",
        .notifications: "bell",
        .profile: "person.crop.circle",
        .wallet: "wallet.pass",
        .cash: "banknote",
        .bank: "building.columns",
        .creditCard: "creditcard",
        .debitCard: "creditcard",
        .savings: "dollarsign.bank.building",
        .investment: "chart.line.uptrend.xyaxis",
        .loan: "hand.raised",
        .mortgage: "house.and.flag",
        .netWorth: "scale.3d",
        .balance: "scale.3d",
        .income: "arrow.down.circle",
        .expense: "arrow.up.circle",
        .transfer: "arrow.left.arrow.right",
        .recurring: "arrow.triangle.2.circlepath",
        .bill: "doc.text",
        .budget: "calendar.badge.clock",
        .goal: "flag",
        .piggyBank: "banknote",
        .chartLine: "chart.line.uptrend.xyaxis",
        .chartBar: "chart.bar",
        .chartPie: "chart.pie",
        .add: "plus",
        .edit: "pencil",
        .delete: "trash",
        .save: "square.and.arrow.down",
        .cancel: "xmark.circle",
        .close: "xmark",
        .check: "checkmark",
        .refresh: "arrow.clockwise",
        .sync: "arrow.triangle.2.circlepath",
        .download: "arrow.down.to.line",
        .upload: "arrow.up.to.line",
        .export: "square.and.arrow.up",
        .import: "tray.and.arrow.down",
        .filter: "line.3.horizontal.decrease.circle",
        .sort: "arrow.up.arrow.down",
        .scan: "viewfinder",
        .copy: "doc.on.doc",
        .share: "square.and.arrow.up",
        .success: "checkmark.circle",
        .warning: "exclamationmark.triangle",
        .error: "exclamationmark.circle",
        .info: "info.circle",
        .pending: "clock",
        .locked: "lock",
        .unlocked: "lock.open",
        .online: "wifi",
        .offline: "wifi.slash",
        .secure: "checkmark.shield",
        .checkingAccount: "building.columns",
        .savingsAccount: "dollarsign.bank.building",
        .cashAccount: "wallet.pass",
        .creditAccount: "creditcard",
        .investmentAccount: "chart.line.uptrend.xyaxis",
        .loanAccount: "hand.raised",
        .mortgageAccount: "house",
        .retirementAccount: "figure.walk",
        .categoryFood: "fork.knife",
        .categoryGroceries: "basket",
        .categoryRestaurants: "fork.knife.circle",
        .categoryTransport: "car",
        .categoryFuel: "fuelpump",
        .categoryShopping: "bag",
        .categoryEntertainment: "popcorn",
        .categoryTravel: "airplane",
        .categoryHealth: "heart.text.square",
        .categoryFitness: "dumbbell",
        .categoryHome: "house",
        .categoryUtilities: "powerplug",
        .categoryEducation: "graduationcap",
        .categoryGifts: "gift",
        .categoryTaxes: "doc.text",
        .categoryInsurance: "shield",
        .categorySubscriptions: "arrow.triangle.2.circlepath",
        .categorySalary: "dollarsign.circle",
    ]
}

func sfSymbolFor(_ token: IconToken) -> String {
    SFSymbolsMapping.mapping[token] ?? token.rawValue
}
