// SPDX-License-Identifier: BUSL-1.1

// AnalyticsModels.swift
// Finance
//
// Data models for advanced analytics and trend prediction features.
// Supports spending forecasts, anomaly detection, and category trends.
//
// References: #269

import SwiftUI

// MARK: - Trend Prediction

/// A predicted future data point generated by trend analysis.
struct TrendPrediction: Identifiable, Sendable {
    let id = UUID()
    let date: Date
    /// Predicted value in minor currency units (cents).
    let predictedMinorUnits: Int64
    /// Upper bound of the confidence interval.
    let upperBoundMinorUnits: Int64
    /// Lower bound of the confidence interval.
    let lowerBoundMinorUnits: Int64
    /// Confidence level as a percentage (0–100).
    let confidencePercent: Double
}

// MARK: - Spending Anomaly

/// A detected anomaly in spending patterns.
struct SpendingAnomaly: Identifiable, Sendable {
    let id = UUID()
    let category: String
    let date: Date
    /// The actual spending amount in minor units.
    let actualMinorUnits: Int64
    /// The expected spending amount based on historical patterns.
    let expectedMinorUnits: Int64
    /// How many standard deviations from the mean this represents.
    let deviationFactor: Double

    /// Whether this anomaly represents overspending.
    var isOverspend: Bool { actualMinorUnits > expectedMinorUnits }

    /// Human-readable severity level.
    var severity: AnomalySeverity {
        if deviationFactor >= 3.0 { return .high }
        if deviationFactor >= 2.0 { return .medium }
        return .low
    }
}

/// Severity level for a spending anomaly.
enum AnomalySeverity: String, Sendable {
    case low, medium, high

    var displayName: String {
        switch self {
        case .low: String(localized: "Low")
        case .medium: String(localized: "Medium")
        case .high: String(localized: "High")
        }
    }

    var color: Color {
        switch self {
        case .low: .yellow
        case .medium: .orange
        case .high: .red
        }
    }

    var systemImage: String {
        switch self {
        case .low: "exclamationmark.triangle"
        case .medium: "exclamationmark.triangle.fill"
        case .high: "xmark.octagon.fill"
        }
    }
}

// MARK: - Category Trend

/// Historical trend data for a specific spending category.
struct CategoryTrend: Identifiable, Sendable {
    let id = UUID()
    let categoryName: String
    let categoryIcon: String
    /// Monthly spending amounts in minor units, oldest first.
    let monthlyAmounts: [MonthlyAmount]
    /// Average monthly spending in minor units.
    let averageMinorUnits: Int64
    /// Month-over-month change as a percentage (-100 to +∞).
    let monthOverMonthChangePercent: Double

    /// Whether spending is trending upward.
    var isTrendingUp: Bool { monthOverMonthChangePercent > 0 }
}

/// A single month's spending amount.
struct MonthlyAmount: Identifiable, Sendable {
    let id = UUID()
    let month: Date
    let amountMinorUnits: Int64
}

// MARK: - Analytics Period

/// Time period for analytics aggregation.
enum AnalyticsPeriod: String, CaseIterable, Sendable {
    case threeMonths = "3M"
    case sixMonths = "6M"
    case oneYear = "1Y"
    case allTime = "All"

    var displayName: String {
        switch self {
        case .threeMonths: String(localized: "3 Months")
        case .sixMonths: String(localized: "6 Months")
        case .oneYear: String(localized: "1 Year")
        case .allTime: String(localized: "All Time")
        }
    }

    /// Number of months to look back.
    var monthCount: Int? {
        switch self {
        case .threeMonths: 3
        case .sixMonths: 6
        case .oneYear: 12
        case .allTime: nil
        }
    }
}

// MARK: - Analytics Summary

/// Top-level analytics summary aggregating all insights.
struct AnalyticsSummary: Sendable {
    let averageMonthlySpending: Int64
    let averageMonthlyIncome: Int64
    let projectedMonthEndSpending: Int64
    let savingsRatePercent: Double
    let topCategories: [CategoryTrend]
    let anomalies: [SpendingAnomaly]
    let predictions: [TrendPrediction]
    let currencyCode: String
}
