// SPDX-License-Identifier: BUSL-1.1

// NotificationModels.swift
// Finance
//
// Data models for notification scheduling and smart alerts.
// Supports budget alerts, bill reminders, goal milestones,
// recurring transaction reminders, and weekly summaries.
//
// References: #305

import SwiftUI

// MARK: - Notification Schedule

/// A scheduled notification rule configured by the user.
struct NotificationSchedule: Identifiable, Sendable, Hashable {
    let id: String
    let type: NotificationType
    let isEnabled: Bool
    let frequency: NotificationFrequency
    /// Time of day for scheduled notifications (hour/minute).
    let scheduledHour: Int
    let scheduledMinute: Int
    /// Optional threshold value (e.g., budget percentage for alerts).
    let thresholdPercent: Double?
    let createdAt: Date

    init(
        id: String = UUID().uuidString,
        type: NotificationType,
        isEnabled: Bool = true,
        frequency: NotificationFrequency = .daily,
        scheduledHour: Int = 9,
        scheduledMinute: Int = 0,
        thresholdPercent: Double? = nil,
        createdAt: Date = .now
    ) {
        self.id = id
        self.type = type
        self.isEnabled = isEnabled
        self.frequency = frequency
        self.scheduledHour = scheduledHour
        self.scheduledMinute = scheduledMinute
        self.thresholdPercent = thresholdPercent
        self.createdAt = createdAt
    }
}

// MARK: - Notification Type

/// Types of financial notifications the app can schedule.
enum NotificationType: String, CaseIterable, Sendable, Hashable {
    case budgetAlert
    case billReminder
    case goalMilestone
    case weeklySummary
    case recurringReminder
    case unusualSpending

    var displayName: String {
        switch self {
        case .budgetAlert: String(localized: "Budget Alerts")
        case .billReminder: String(localized: "Bill Reminders")
        case .goalMilestone: String(localized: "Goal Milestones")
        case .weeklySummary: String(localized: "Weekly Summary")
        case .recurringReminder: String(localized: "Recurring Transactions")
        case .unusualSpending: String(localized: "Unusual Spending")
        }
    }

    var description: String {
        switch self {
        case .budgetAlert:
            String(localized: "Get notified when spending approaches budget limits")
        case .billReminder:
            String(localized: "Reminders before recurring bills are due")
        case .goalMilestone:
            String(localized: "Celebrate when you reach savings goal milestones")
        case .weeklySummary:
            String(localized: "A weekly overview of your spending and savings")
        case .recurringReminder:
            String(localized: "Reminders for upcoming recurring transactions")
        case .unusualSpending:
            String(localized: "Alerts when spending patterns seem unusual")
        }
    }

    var systemImage: String {
        switch self {
        case .budgetAlert: "chart.pie"
        case .billReminder: "calendar.badge.clock"
        case .goalMilestone: "target"
        case .weeklySummary: "chart.bar.doc.horizontal"
        case .recurringReminder: "arrow.clockwise"
        case .unusualSpending: "exclamationmark.triangle"
        }
    }

    var categoryIdentifier: String {
        "finance.\(rawValue)"
    }
}

// MARK: - Notification Frequency

/// How often a notification should be delivered.
enum NotificationFrequency: String, CaseIterable, Sendable, Hashable {
    case daily, weekly, monthly

    var displayName: String {
        switch self {
        case .daily: String(localized: "Daily")
        case .weekly: String(localized: "Weekly")
        case .monthly: String(localized: "Monthly")
        }
    }
}

// MARK: - Smart Alert

/// A smart alert generated by analyzing financial data.
struct SmartAlert: Identifiable, Sendable {
    let id: String
    let type: NotificationType
    let title: String
    let body: String
    let priority: AlertPriority
    let createdAt: Date
    let actionURL: String?

    init(
        id: String = UUID().uuidString,
        type: NotificationType,
        title: String,
        body: String,
        priority: AlertPriority = .normal,
        createdAt: Date = .now,
        actionURL: String? = nil
    ) {
        self.id = id
        self.type = type
        self.title = title
        self.body = body
        self.priority = priority
        self.createdAt = createdAt
        self.actionURL = actionURL
    }
}

/// Priority level for smart alerts.
enum AlertPriority: String, Sendable, Comparable {
    case low, normal, high, urgent

    var displayName: String {
        switch self {
        case .low: String(localized: "Low")
        case .normal: String(localized: "Normal")
        case .high: String(localized: "High")
        case .urgent: String(localized: "Urgent")
        }
    }

    var color: Color {
        switch self {
        case .low: .secondary
        case .normal: .blue
        case .high: .orange
        case .urgent: .red
        }
    }

    private var sortOrder: Int {
        switch self {
        case .low: 0
        case .normal: 1
        case .high: 2
        case .urgent: 3
        }
    }

    static func < (lhs: AlertPriority, rhs: AlertPriority) -> Bool {
        lhs.sortOrder < rhs.sortOrder
    }
}
