// SPDX-License-Identifier: BUSL-1.1

package com.finance.android.monitoring

/**
 * Baseline profile configuration for startup optimisation.
 *
 * Android's Baseline Profiles pre-compile critical code paths into
 * AOT-compiled native code on install, improving cold start time
 * and reducing jank during the first few frames.
 *
 * ## Generating Profiles
 * Profiles are generated by running instrumented tests that exercise
 * critical user journeys. The generated `baseline-prof.txt` is shipped
 * with the APK/AAB.
 *
 * Run:
 * ```bash
 * ./gradlew :apps:android:generateBaselineProfile
 * ```
 *
 * ## Critical Paths Profiled
 * 1. App cold start → Dashboard screen visible
 * 2. Navigation to Transactions list
 * 3. Navigation to Accounts list
 * 4. Transaction creation flow
 * 5. Settings screen load
 *
 * ## Privacy
 * Baseline profiles contain only class/method references — no user
 * data or financial information.
 *
 * @see [baseline-prof.txt] in `src/main/` for the generated profile.
 */
object BaselineProfileGenerator {

    /**
     * Critical composable routes that should be included in the
     * baseline profile.
     *
     * These are used by the profile generation test to navigate
     * through the most important screens.
     */
    val criticalRoutes = listOf(
        "dashboard",
        "accounts",
        "transactions",
        "budgets",
        "goals",
        "settings",
    )

    /**
     * Critical Koin-injected classes that should be pre-initialized
     * during profiling to capture their class loading in the profile.
     */
    val criticalDependencies = listOf(
        "DashboardViewModel",
        "AccountsViewModel",
        "TransactionsViewModel",
        "BudgetsViewModel",
        "GoalsViewModel",
    )
}