// SPDX-License-Identifier: BUSL-1.1

import { Currencies, cents, type Cents, type Currency, type SyncMetadata } from '../../kmp/bridge';
import type { Row } from '../sqlite-wasm';

/** SQL expression for an ISO-8601 UTC timestamp generated by SQLite. */
export const SQLITE_NOW_EXPRESSION = "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')";

/** Read a required string field from a database row. */
export function requireString(value: unknown, field: string): string {
  if (typeof value === 'string') {
    return value;
  }

  if (value === null || value === undefined) {
    throw new Error(`Missing required field: ${field}`);
  }

  return String(value);
}

/** Read a required numeric field from a database row. */
export function requireNumber(value: unknown, field: string): number {
  if (typeof value === 'number') {
    return value;
  }

  if (typeof value === 'bigint') {
    return Number(value);
  }

  if (typeof value === 'string' && value.trim().length > 0) {
    const parsed = Number(value);
    if (!Number.isNaN(parsed)) {
      return parsed;
    }
  }

  throw new Error(`Invalid numeric field: ${field}`);
}

/** Read an optional string field from a database row. */
export function optionalString(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null;
  }

  return typeof value === 'string' ? value : String(value);
}

/** Convert SQLite boolean-ish values into JavaScript booleans. */
export function toBoolean(value: unknown): boolean {
  if (typeof value === 'boolean') {
    return value;
  }

  if (typeof value === 'number') {
    return value !== 0;
  }

  if (typeof value === 'bigint') {
    return value !== 0n;
  }

  if (typeof value === 'string') {
    return value === '1' || value.toLowerCase() === 'true';
  }

  return false;
}

/** Convert a stored ISO currency code into a bridge Currency object. */
export function mapCurrency(value: unknown): Currency {
  const code = requireString(value, 'currency').toUpperCase();
  return Currencies[code as keyof typeof Currencies] ?? { code, decimalPlaces: 2 };
}

/** Convert a stored integer amount into a bridge Cents object. */
export function mapCents(value: unknown, field: string): Cents {
  return cents(requireNumber(value, field));
}

/** Map shared sync metadata columns into the bridge shape. */
export function mapSyncMetadata(row: Row): SyncMetadata {
  return {
    createdAt: requireString(row.created_at, 'created_at'),
    updatedAt: requireString(row.updated_at, 'updated_at'),
    deletedAt: optionalString(row.deleted_at),
    syncVersion: requireNumber(row.sync_version, 'sync_version'),
    isSynced: toBoolean(row.is_synced),
  };
}

/** Serialize a string-tag list for SQLite JSON text storage. */
export function serializeTags(tags: readonly string[]): string {
  return JSON.stringify([...tags]);
}

/** Parse a JSON-encoded tag list from SQLite storage. */
export function parseTags(value: unknown): readonly string[] {
  if (typeof value !== 'string' || value.trim().length === 0) {
    return [];
  }

  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed.map((entry) => String(entry)) : [];
  } catch {
    return [];
  }
}

/** Build a safe SQL LIKE pattern for user-entered text. */
export function createLikePattern(value: string): string {
  return `%${value.trim()}%`;
}
