// SPDX-License-Identifier: BUSL-1.1

/**
 * In-context transaction collaboration engine.
 *
 * Supports attaching notes/comments to transactions, tagging transactions
 * for partner review, managing a review queue per member, and building
 * collaboration threads.
 *
 * All functions are pure. IDs are expected to be pre-generated by the caller.
 *
 * References: issues #1789, #1790
 */

import type { SyncId } from '../../kmp/bridge';
import type {
  CollaborationNote,
  CollaborationThread,
  ReviewItem,
  ReviewStatus,
  TagForReviewInput,
} from './types';

// ---------------------------------------------------------------------------
// Notes / comments
// ---------------------------------------------------------------------------

/**
 * Add a note to a transaction.
 *
 * @param existingNotes - Current notes
 * @param note - The new note to add (must have a pre-generated id)
 * @returns Updated array of notes
 */
export function addNote(
  existingNotes: readonly CollaborationNote[],
  note: CollaborationNote,
): CollaborationNote[] {
  return [...existingNotes, note];
}

/**
 * Get all notes for a specific transaction, sorted by creation time.
 *
 * @param notes - All notes
 * @param transactionId - Transaction to filter for
 * @returns Notes for the transaction, oldest first
 */
export function getTransactionNotes(
  notes: readonly CollaborationNote[],
  transactionId: SyncId,
): CollaborationNote[] {
  return notes
    .filter((n) => n.transactionId === transactionId)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt));
}

/**
 * Count notes on a transaction.
 *
 * @param notes - All notes
 * @param transactionId - Transaction to count for
 * @returns Number of notes
 */
export function countTransactionNotes(
  notes: readonly CollaborationNote[],
  transactionId: SyncId,
): number {
  return notes.filter((n) => n.transactionId === transactionId).length;
}

// ---------------------------------------------------------------------------
// Tag-for-review workflow
// ---------------------------------------------------------------------------

/**
 * Create a review item by tagging a transaction for partner review.
 *
 * @param existingItems - Current review items
 * @param input - Review tagging input
 * @param id - Pre-generated ID for the review item
 * @param now - Current timestamp (ISO-8601)
 * @returns Updated array of review items
 */
export function tagForReview(
  existingItems: readonly ReviewItem[],
  input: TagForReviewInput,
  id: SyncId,
  now: string,
): ReviewItem[] {
  const newItem: ReviewItem = {
    id,
    transactionId: input.transactionId,
    flaggedBy: input.flaggedBy,
    assignedTo: input.assignedTo,
    status: 'PENDING',
    reason: input.reason,
    createdAt: now,
    resolvedAt: null,
  };

  return [...existingItems, newItem];
}

/**
 * Resolve a review item by approving or rejecting it.
 *
 * @param items - All review items
 * @param reviewId - ID of the review item to resolve
 * @param status - New status (APPROVED or REJECTED)
 * @param now - Current timestamp (ISO-8601)
 * @returns Updated array of review items
 */
export function resolveReview(
  items: readonly ReviewItem[],
  reviewId: SyncId,
  status: 'APPROVED' | 'REJECTED',
  now: string,
): ReviewItem[] {
  return items.map((item) => (item.id === reviewId ? { ...item, status, resolvedAt: now } : item));
}

/**
 * Get the review queue for a specific member (items assigned to them).
 *
 * @param items - All review items
 * @param memberId - The member whose queue to retrieve
 * @param statusFilter - Optional status filter (defaults to all)
 * @returns Review items assigned to the member, newest first
 */
export function getReviewQueue(
  items: readonly ReviewItem[],
  memberId: SyncId,
  statusFilter?: ReviewStatus,
): ReviewItem[] {
  return items
    .filter(
      (item) =>
        item.assignedTo === memberId &&
        (statusFilter === undefined || item.status === statusFilter),
    )
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/**
 * Get pending review items for a member.
 *
 * @param items - All review items
 * @param memberId - The member to check
 * @returns Pending review items assigned to the member
 */
export function getPendingReviews(items: readonly ReviewItem[], memberId: SyncId): ReviewItem[] {
  return getReviewQueue(items, memberId, 'PENDING');
}

/**
 * Count pending reviews for a member (badge count).
 *
 * @param items - All review items
 * @param memberId - The member to check
 * @returns Number of pending reviews
 */
export function countPendingReviews(items: readonly ReviewItem[], memberId: SyncId): number {
  return getPendingReviews(items, memberId).length;
}

/**
 * Get the review item for a specific transaction, if any.
 *
 * Returns the most recent review item for the transaction.
 *
 * @param items - All review items
 * @param transactionId - Transaction to look up
 * @returns The most recent review item, or null
 */
export function getTransactionReview(
  items: readonly ReviewItem[],
  transactionId: SyncId,
): ReviewItem | null {
  const matching = items
    .filter((item) => item.transactionId === transactionId)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));

  return matching[0] ?? null;
}

// ---------------------------------------------------------------------------
// Collaboration thread
// ---------------------------------------------------------------------------

/**
 * Build a collaboration thread for a transaction.
 *
 * Combines notes and the review item (if any) into a single thread object.
 *
 * @param notes - All collaboration notes
 * @param reviewItems - All review items
 * @param transactionId - Transaction to build the thread for
 * @returns Collaboration thread with notes and optional review item
 */
export function buildCollaborationThread(
  notes: readonly CollaborationNote[],
  reviewItems: readonly ReviewItem[],
  transactionId: SyncId,
): CollaborationThread {
  return {
    transactionId,
    notes: getTransactionNotes(notes, transactionId),
    reviewItem: getTransactionReview(reviewItems, transactionId),
  };
}

/**
 * Get all transactions that have collaboration activity (notes or reviews).
 *
 * @param notes - All collaboration notes
 * @param reviewItems - All review items
 * @returns Unique transaction IDs with collaboration activity
 */
export function getTransactionsWithCollaboration(
  notes: readonly CollaborationNote[],
  reviewItems: readonly ReviewItem[],
): SyncId[] {
  const ids = new Set<SyncId>();
  for (const note of notes) ids.add(note.transactionId);
  for (const item of reviewItems) ids.add(item.transactionId);
  return Array.from(ids);
}
