// SPDX-License-Identifier: BUSL-1.1
import XCTest
@testable import FinanceApp
final class CategoriesViewModelTests: XCTestCase {
    @MainActor func testLoadPopulates() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); XCTAssertEqual(vm.categories.count, SampleData.allCategories.count); XCTAssertFalse(vm.isLoading) }
    @MainActor func testLoadEmpty() async { let vm = CategoriesViewModel(repository: StubCategoryRepository()); await vm.loadCategories(); XCTAssertTrue(vm.categories.isEmpty) }
    @MainActor func testLoadError() async { let r = StubCategoryRepository(); r.errorToThrow = TestError.simulated; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); XCTAssertTrue(vm.categories.isEmpty); XCTAssertTrue(vm.showError); XCTAssertFalse(vm.isLoading) }
    @MainActor func testCreate() async { let r = StubCategoryRepository(); let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); await vm.createCategory(name: "Travel", colorHex: "#2196F3", iconName: "airplane"); XCTAssertEqual(vm.categories.count, 1); XCTAssertEqual(vm.categories.first?.name, "Travel"); XCTAssertEqual(r.createdInputs.count, 1) }
    @MainActor func testCreateError() async { let r = StubCategoryRepository(); let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); r.errorToThrow = TestError.simulated; await vm.createCategory(name: "Fail", colorHex: "#F00", iconName: "xmark"); XCTAssertTrue(vm.categories.isEmpty); XCTAssertTrue(vm.showError) }
    @MainActor func testUpdate() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); let o = vm.categories[0]; await vm.updateCategory(id: o.id, name: "Renamed", colorHex: "#FF0000", iconName: "star"); XCTAssertEqual(vm.categories.first(where: { $0.id == o.id })?.name, "Renamed") }
    @MainActor func testUpdateError() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); r.errorToThrow = TestError.simulated; let o = vm.categories[0]; await vm.updateCategory(id: o.id, name: "Fail", colorHex: "#F00", iconName: "xmark"); XCTAssertTrue(vm.showError); XCTAssertEqual(vm.categories.first(where: { $0.id == o.id })?.name, o.name) }
    @MainActor func testDelete() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); let c = vm.categories.count; let id = vm.categories[0].id; await vm.deleteCategory(id: id); XCTAssertEqual(vm.categories.count, c - 1); XCTAssertNil(vm.categories.first(where: { $0.id == id })); XCTAssertEqual(r.deletedIds, [id]) }
    @MainActor func testDeleteError() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); let c = vm.categories.count; r.errorToThrow = TestError.simulated; await vm.deleteCategory(id: vm.categories[0].id); XCTAssertTrue(vm.showError); XCTAssertEqual(vm.categories.count, c) }
    @MainActor func testReorder() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); let n = vm.categories[0].name; vm.reorderCategories(fromOffsets: IndexSet(integer: 0), toOffset: 2); XCTAssertEqual(vm.categories[1].name, n) }
    @MainActor func testSearchFilter() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); vm.searchText = "Food"; XCTAssertEqual(vm.categories.count, 1); XCTAssertEqual(vm.categories.first?.name, "Food & Groceries") }
    @MainActor func testSearchEmpty() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); vm.searchText = "Food"; XCTAssertEqual(vm.categories.count, 1); vm.searchText = ""; XCTAssertEqual(vm.categories.count, SampleData.allCategories.count) }
    @MainActor func testSearchCaseInsensitive() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); vm.searchText = "food"; XCTAssertEqual(vm.categories.count, 1); vm.searchText = "FOOD"; XCTAssertEqual(vm.categories.count, 1) }
    @MainActor func testSearchNoMatch() async { let r = StubCategoryRepository(); r.categoriesToReturn = SampleData.allCategories; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); vm.searchText = "zzzznonexistent"; XCTAssertTrue(vm.categories.isEmpty) }
    @MainActor func testDismissError() async { let r = StubCategoryRepository(); r.errorToThrow = TestError.simulated; let vm = CategoriesViewModel(repository: r); await vm.loadCategories(); XCTAssertTrue(vm.showError); vm.dismissError(); XCTAssertFalse(vm.showError); XCTAssertNil(vm.errorMessage) }
}