// SPDX-License-Identifier: BUSL-1.1

export const ICON_TOKENS = [
  'HOME',
  'DASHBOARD',
  'ACCOUNTS',
  'TRANSACTIONS',
  'BUDGETS',
  'GOALS',
  'REPORTS',
  'INSIGHTS',
  'SETTINGS',
  'SEARCH',
  'NOTIFICATIONS',
  'PROFILE',
  'WALLET',
  'CASH',
  'BANK',
  'CREDIT_CARD',
  'DEBIT_CARD',
  'SAVINGS',
  'INVESTMENT',
  'LOAN',
  'MORTGAGE',
  'NET_WORTH',
  'BALANCE',
  'INCOME',
  'EXPENSE',
  'TRANSFER',
  'RECURRING',
  'BILL',
  'BUDGET',
  'GOAL',
  'PIGGY_BANK',
  'CHART_LINE',
  'CHART_BAR',
  'CHART_PIE',
  'ADD',
  'EDIT',
  'DELETE',
  'SAVE',
  'CANCEL',
  'CLOSE',
  'CHECK',
  'REFRESH',
  'SYNC',
  'DOWNLOAD',
  'UPLOAD',
  'EXPORT',
  'IMPORT',
  'FILTER',
  'SORT',
  'SCAN',
  'COPY',
  'SHARE',
  'SUCCESS',
  'WARNING',
  'ERROR',
  'INFO',
  'PENDING',
  'LOCKED',
  'UNLOCKED',
  'ONLINE',
  'OFFLINE',
  'SECURE',
  'CHECKING_ACCOUNT',
  'SAVINGS_ACCOUNT',
  'CASH_ACCOUNT',
  'CREDIT_ACCOUNT',
  'INVESTMENT_ACCOUNT',
  'LOAN_ACCOUNT',
  'MORTGAGE_ACCOUNT',
  'RETIREMENT_ACCOUNT',
  'CATEGORY_FOOD',
  'CATEGORY_GROCERIES',
  'CATEGORY_RESTAURANTS',
  'CATEGORY_TRANSPORT',
  'CATEGORY_FUEL',
  'CATEGORY_SHOPPING',
  'CATEGORY_ENTERTAINMENT',
  'CATEGORY_TRAVEL',
  'CATEGORY_HEALTH',
  'CATEGORY_FITNESS',
  'CATEGORY_HOME',
  'CATEGORY_UTILITIES',
  'CATEGORY_EDUCATION',
  'CATEGORY_GIFTS',
  'CATEGORY_TAXES',
  'CATEGORY_INSURANCE',
  'CATEGORY_SUBSCRIPTIONS',
  'CATEGORY_SALARY',
] as const;

export type IconToken = (typeof ICON_TOKENS)[number];

export const IconToken = Object.fromEntries(ICON_TOKENS.map((token) => [token, token])) as {
  readonly [Token in IconToken]: Token;
};

export type IconMapping = Record<IconToken, string>;

export const STANDARD_LUCIDE = 'standard_lucide';
export const IOS_SF_SYMBOLS = 'ios_sf_symbols';
export const MATERIAL_SYMBOLS_OUTLINED = 'material_symbols_outlined';
export const MATERIAL_SYMBOLS_ROUNDED = 'material_symbols_rounded';
export const MATERIAL_SYMBOLS_SHARP = 'material_symbols_sharp';
export const FLUENT_REGULAR = 'fluent_regular';
export const FLUENT_FILLED = 'fluent_filled';

export const ICON_PACK_PREFERENCE_KEY = 'icon_pack_id';

export type IconPackId =
  | typeof STANDARD_LUCIDE
  | typeof IOS_SF_SYMBOLS
  | typeof MATERIAL_SYMBOLS_OUTLINED
  | typeof MATERIAL_SYMBOLS_ROUNDED
  | typeof MATERIAL_SYMBOLS_SHARP
  | typeof FLUENT_REGULAR
  | typeof FLUENT_FILLED;

export const LUCIDE_MAPPING: IconMapping = {
  HOME: 'home',
  DASHBOARD: 'layout-dashboard',
  ACCOUNTS: 'users',
  TRANSACTIONS: 'receipt-text',
  BUDGETS: 'calculator',
  GOALS: 'target',
  REPORTS: 'chart-column',
  INSIGHTS: 'lightbulb',
  SETTINGS: 'settings',
  SEARCH: 'search',
  NOTIFICATIONS: 'bell',
  PROFILE: 'circle-user-round',
  WALLET: 'wallet',
  CASH: 'banknote',
  BANK: 'landmark',
  CREDIT_CARD: 'credit-card',
  DEBIT_CARD: 'credit-card',
  SAVINGS: 'piggy-bank',
  INVESTMENT: 'trending-up',
  LOAN: 'hand-coins',
  MORTGAGE: 'house-plus',
  NET_WORTH: 'scale',
  BALANCE: 'scale',
  INCOME: 'arrow-down-to-line',
  EXPENSE: 'arrow-up-from-line',
  TRANSFER: 'arrow-left-right',
  RECURRING: 'repeat',
  BILL: 'file-text',
  BUDGET: 'calculator',
  GOAL: 'flag',
  PIGGY_BANK: 'piggy-bank',
  CHART_LINE: 'chart-line',
  CHART_BAR: 'chart-bar',
  CHART_PIE: 'chart-pie',
  ADD: 'plus',
  EDIT: 'pencil',
  DELETE: 'trash-2',
  SAVE: 'save',
  CANCEL: 'circle-x',
  CLOSE: 'x',
  CHECK: 'check',
  REFRESH: 'refresh-cw',
  SYNC: 'refresh-ccw',
  DOWNLOAD: 'download',
  UPLOAD: 'upload',
  EXPORT: 'file-up',
  IMPORT: 'file-down',
  FILTER: 'funnel',
  SORT: 'arrow-up-down',
  SCAN: 'scan-line',
  COPY: 'copy',
  SHARE: 'share-2',
  SUCCESS: 'circle-check',
  WARNING: 'triangle-alert',
  ERROR: 'circle-alert',
  INFO: 'info',
  PENDING: 'clock',
  LOCKED: 'lock',
  UNLOCKED: 'lock-open',
  ONLINE: 'wifi',
  OFFLINE: 'wifi-off',
  SECURE: 'shield-check',
  CHECKING_ACCOUNT: 'landmark',
  SAVINGS_ACCOUNT: 'piggy-bank',
  CASH_ACCOUNT: 'wallet',
  CREDIT_ACCOUNT: 'credit-card',
  INVESTMENT_ACCOUNT: 'chart-line',
  LOAN_ACCOUNT: 'hand-coins',
  MORTGAGE_ACCOUNT: 'house',
  RETIREMENT_ACCOUNT: 'palm-tree',
  CATEGORY_FOOD: 'utensils',
  CATEGORY_GROCERIES: 'shopping-basket',
  CATEGORY_RESTAURANTS: 'chef-hat',
  CATEGORY_TRANSPORT: 'car',
  CATEGORY_FUEL: 'fuel',
  CATEGORY_SHOPPING: 'shopping-bag',
  CATEGORY_ENTERTAINMENT: 'popcorn',
  CATEGORY_TRAVEL: 'plane',
  CATEGORY_HEALTH: 'heart-pulse',
  CATEGORY_FITNESS: 'dumbbell',
  CATEGORY_HOME: 'house',
  CATEGORY_UTILITIES: 'plug',
  CATEGORY_EDUCATION: 'graduation-cap',
  CATEGORY_GIFTS: 'gift',
  CATEGORY_TAXES: 'receipt',
  CATEGORY_INSURANCE: 'shield',
  CATEGORY_SUBSCRIPTIONS: 'repeat',
  CATEGORY_SALARY: 'badge-dollar-sign',
};

export { MATERIAL_SYMBOLS_OUTLINED_MAPPING } from './materialSymbolsOutlined';
export { MATERIAL_SYMBOLS_ROUNDED_MAPPING } from './materialSymbolsRounded';
export { MATERIAL_SYMBOLS_SHARP_MAPPING } from './materialSymbolsSharp';
export { FLUENT_REGULAR_MAPPING } from './fluentRegular';
export { FLUENT_FILLED_MAPPING } from './fluentFilled';

export default LUCIDE_MAPPING;
