# SPDX-License-Identifier: BUSL-1.1
# =============================================================================
# Finance App - Local Supabase Setup Script (PowerShell)
# =============================================================================
# Usage:
#   .\services\api\scripts\setup-local.ps1       # from repo root
#   .\scripts\setup-local.ps1                    # from services\api\
#
# What it does:
#   1. Verifies prerequisites (Docker, Supabase CLI)
#   2. Starts local Supabase stack (supabase start)
#   3. Migrations are applied automatically by the CLI
#   4. Seeds the database with test data
#   5. Prints connection info and generated keys
# =============================================================================

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ApiDir      = Split-Path -Parent $ScriptDir
$SupabaseDir = Join-Path $ApiDir "supabase"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Info  { param([string]$msg) Write-Host "i  $msg" -ForegroundColor Cyan }
function Ok    { param([string]$msg) Write-Host "+  $msg" -ForegroundColor Green }
function Warn  { param([string]$msg) Write-Host "!  $msg" -ForegroundColor Yellow }
function Fail  { param([string]$msg) Write-Host "x  $msg" -ForegroundColor Red; exit 1 }

# ---------------------------------------------------------------------------
# Step 1 - Check prerequisites
# ---------------------------------------------------------------------------
Info "Checking prerequisites ..."

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Fail "Docker is not installed. Install Docker Desktop: https://www.docker.com/products/docker-desktop/"
}

try {
    docker info 2>&1 | Out-Null
} catch {
    Fail "Docker daemon is not running. Please start Docker Desktop and retry."
}

Ok "Docker is available"

# Resolve the Supabase CLI: prefer a global install, else fall back to `npx`.
# This keeps the script seamless on machines without a global CLI (e.g. a fresh
# Windows dev box) - `npx --yes supabase` downloads/caches it on first use.
if (Get-Command supabase -ErrorAction SilentlyContinue) {
    $script:SbExe  = "supabase"
    $script:SbBase = @()
} elseif (Get-Command npx -ErrorAction SilentlyContinue) {
    $script:SbExe  = "npx"
    $script:SbBase = @("--yes", "supabase")
    Warn "Global 'supabase' CLI not found - falling back to 'npx --yes supabase'."
} else {
    Fail "Neither 'supabase' nor 'npx' is available. Install Node.js (for npx) or the Supabase CLI."
}

function Invoke-Supa { & $script:SbExe @($script:SbBase + $args) }

$sbVersion = (Invoke-Supa --version 2>&1) -join " "
Ok "Supabase CLI is available ($sbVersion)"

# ---------------------------------------------------------------------------
# Step 2 - Start Supabase (migrations run automatically)
# ---------------------------------------------------------------------------
Info "Starting local Supabase stack ..."
Info "Working directory: $SupabaseDir"

Push-Location $ApiDir

try {
    $output = Invoke-Supa start 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host $output
        Fail "supabase start failed - see output above."
    }
    Ok "Supabase stack is running"
} catch {
    Fail "supabase start failed: $_"
}

# ---------------------------------------------------------------------------
# Step 3 - Seed database
# ---------------------------------------------------------------------------
Info "Applying seed data ..."

$seedFile = Join-Path $SupabaseDir "seed.sql"
if (Test-Path $seedFile) {
    $resetOut = Invoke-Supa db reset 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host $resetOut
        Fail "supabase db reset failed - a migration or seed step errored (see output above)."
    }
    Ok "Database reset with migrations and seed data applied"
} else {
    Warn "No seed.sql found - skipping seed step."
}

# ---------------------------------------------------------------------------
# Step 3.5 - Wire the web app to this local stack (apps/web/.env.local)
# ---------------------------------------------------------------------------
Info "Writing apps/web/.env.local (local full-stack profile) ..."

$RepoRoot    = Split-Path -Parent (Split-Path -Parent $ApiDir)
$WebEnvLocal = Join-Path $RepoRoot "apps/web/.env.local"

$statusEnv = Invoke-Supa status "-o" "env" 2>$null
$envMap = @{}
foreach ($line in $statusEnv) {
    if ($line -match '^\s*([A-Z0-9_]+)\s*=\s*"?(.*?)"?\s*$') {
        $envMap[$matches[1]] = $matches[2]
    }
}
$apiUrl  = if ($envMap["API_URL"]) { $envMap["API_URL"] } else { "http://localhost:54321" }
$anonKey = $envMap["ANON_KEY"]

if ($anonKey) {
    $webEnv = @"
# Generated by services/api/scripts/setup-local.ps1 - local full-stack (edge) profile.
# Points the web app at the local Supabase CLI stack so it exercises real edge
# auth (GoTrue + auth-* edge functions + Postgres/RLS) instead of demo mode.
# Safe to delete and regenerate: npm --prefix services/api run setup:windows
VITE_SUPABASE_URL=$apiUrl
VITE_SUPABASE_ANON_KEY=$anonKey
VITE_FUNCTIONS_PROXY_TARGET=$apiUrl
"@
    Set-Content -Path $WebEnvLocal -Value $webEnv -Encoding utf8
    Ok "Wrote $WebEnvLocal"
} else {
    Warn "Could not read the anon key from 'supabase status' - skipping apps/web/.env.local."
    Warn "Set VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY manually (see apps/web/.env.example)."
}

# ---------------------------------------------------------------------------
# Step 4 - Print status
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "================================================================" -ForegroundColor White
Write-Host "  Finance - Local Supabase Stack" -ForegroundColor White
Write-Host "================================================================" -ForegroundColor White
Write-Host ""

Invoke-Supa status 2>&1 | Write-Host

Write-Host ""
Write-Host "Quick links:" -ForegroundColor White
Write-Host "  Studio UI       -> http://localhost:54323" -ForegroundColor Cyan
Write-Host "  API (PostgREST) -> http://localhost:54321" -ForegroundColor Cyan
Write-Host "  Database        -> postgresql://postgres:postgres@localhost:54322/postgres" -ForegroundColor Cyan
Write-Host "  Inbucket (mail) -> http://localhost:54324" -ForegroundColor Cyan

Write-Host ""
Write-Host "Useful commands:" -ForegroundColor White
Write-Host "  npm run supabase:stop      - Stop the stack"
Write-Host "  npm run supabase:reset     - Reset DB with migrations + seed"
Write-Host "  npm run supabase:migrate   - Apply pending migrations only"
Write-Host "  npm run supabase:functions - Run Edge Functions locally"

Write-Host ""
Write-Host "Next - run the web app against this stack:" -ForegroundColor White
Write-Host "  1. npm install                          (repo root, first time only)"
Write-Host "  2. npm run dev -w apps/web              -> http://localhost:5173 (uses apps/web/.env.local)"
Write-Host "  3. npm run test:e2e:live -w apps/web    (real-backend signup/login smoke)"
Write-Host "  Full runbook: docs/guides/full-stack-local.md" -ForegroundColor Cyan
Write-Host ""

Pop-Location
